from .tasks import task_bp
from .users import user_bp
from .auth import auth_bp
from .health import health_bp
from .workspace import workspace_bp
from .project import project_bp
from .workspace_member import workspace_member_bp
from .workspace_invitation import workspace_invitation_bp
from .comments import comment_bp
from .time_blocks import time_block_bp
from .admin import admin_bp
from .analytics import analytic_bp